export const metadata = {
    title: "Admin",
    description: "generated by next app"
}

export default function RootLayout({children}){
    return(
        <html lang="en" dir="rtl">
            <body>
                {children}
            </body>
        </html>
    )
}