import { Geist, Geist_Mono } from "next/font/google";
import { DynaPuff } from "next/font/google";
import "./globals.css";
import Footer from "./layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dynaPuff = DynaPuff({
  variable: "--font-dynapuff",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${dynaPuff.variable}
        `}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
